/*
Copyright 2021 Lars Eric Scheidler

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package global

import (
	"github.com/lscheidler/letsencrypt-deploy/provider/fortios/api/v2"
)

type Global struct {
	Results *result `json:"results"`
}

type result struct {
	AdminServerCert *v2.ServerCert `json:"admin-server-cert"`
}

/*
/api/v2/cmdb/system/global?datasource=1&with_meta=1
{ "http_method": "GET",
"revision": "7d80526c65207069a2009f89aa4e63f0",
"results": { "language": "english",
"gui-ipv6": "disable",
"gui-certificates": "enable",
"gui-custom-language": "disable",
"gui-wireless-opensecurity": "disable",
"gui-display-hostname": "disable",
"gui-fortisandbox-cloud": "disable",
"gui-lines-per-page": 50,
"admin-https-ssl-versions": "tlsv1-1 tlsv1-2 tlsv1-3",
"admintimeout": 5,
"admin-console-timeout": 0,
"ssd-trim-freq": "weekly",
"ssd-trim-hour": 1,
"ssd-trim-min": 60,
"ssd-trim-weekday": "sunday",
"ssd-trim-date": 1,
"admin-concurrent": "enable",
"admin-lockout-threshold": 3,
"admin-lockout-duration": 60,
"refresh": 0,
"interval": 5,
"failtime": 5,
"daily-restart": "disable",
"restart-time": "00:00",
"radius-port": 1812,
"admin-login-max": 100,
"remoteauthtimeout": 5,
"ldapconntimeout": 500,
"batch-cmdb": "enable",
"multi-factor-authentication": "optional",
"ssl-min-proto-version": "TLSv1-2",
"autorun-log-fsck": "disable",
"dst": "enable",
"timezone": "26",
"traffic-priority": "tos",
"traffic-priority-level": "medium",
"anti-replay": "loose",
"send-pmtu-icmp": "enable",
"honor-df": "enable",
"revision-image-auto-backup": "enable",
"revision-backup-on-logout": "enable",
"management-vdom": { "q_origin_key": "root",
"name": "root",
"datasource": "system.vdom",
"css-class": "ftnt-vdom" },
"hostname": "staging-fw-1",
"gui-allow-default-hostname": "disable",
"alias": "FGTAWS0007B7604F",
"strong-crypto": "enable",
"ssh-cbc-cipher": "enable",
"ssh-hmac-md5": "enable",
"ssh-kex-sha1": "enable",
"ssh-mac-weak": "enable",
"ssl-static-key-ciphers": "enable",
"snat-route-change": "disable",
"cli-audit-log": "disable",
"dh-params": "2048",
"fds-statistics": "enable",
"fds-statistics-period": 60,
"tcp-option": "enable",
"lldp-transmission": "disable",
"lldp-reception": "disable",
"proxy-auth-timeout": 5,
"proxy-re-authentication-mode": "session",
"proxy-auth-lifetime": "disable",
"proxy-auth-lifetime-timeout": 480,
"sys-perf-log-interval": 5,
"check-protocol-header": "loose",
"vip-arp-range": "restricted",
"reset-sessionless-tcp": "disable",
"allow-traffic-redirect": "enable",
"strict-dirty-session-check": "enable",
"tcp-halfclose-timer": 120,
"tcp-halfopen-timer": 10,
"tcp-timewait-timer": 1,
"udp-idle-timer": 180,
"block-session-timer": 30,
"ip-src-port-range": "1024-25000",
"pre-login-banner": "disable",
"post-login-banner": "disable",
"tftp": "enable",
"av-failopen": "pass",
"av-failopen-session": "disable",
"memory-use-threshold-extreme": 95,
"memory-use-threshold-red": 88,
"memory-use-threshold-green": 82,
"cpu-use-threshold": 90,
"check-reset-range": "disable",
"vdom-mode": "no-vdom",
"vdom-admin": "",
"long-vdom-name": "disable",
"admin-port": 80,
"admin-sport": 10443,
"admin-https-redirect": "enable",
"admin-hsts-max-age": 15552000,
"admin-ssh-password": "disable",
"admin-restrict-local": "disable",
"admin-ssh-port": 1022,
"admin-ssh-grace-time": 120,
"admin-ssh-v1": "disable",
"admin-telnet": "enable",
"admin-telnet-port": 23,
"default-service-source-port": "1-65535",
"admin-maintainer": "enable",
"admin-server-cert": { "q_origin_key": "<name>",
"name": "<name>",
"datasource": "certificate.local" },
"user-server-cert": { "q_origin_key": "Fortinet_Factory",
"name": "Fortinet_Factory",
"datasource": "certificate.local" },
"admin-https-pki-required": "disable",
"wifi-certificate": { "q_origin_key": "Fortinet_Wifi",
"name": "Fortinet_Wifi",
"datasource": "certificate.local" },
"wifi-ca-certificate": { "q_origin_key": "Fortinet_Wifi_CA",
"name": "Fortinet_Wifi_CA",
"datasource": "certificate.ca" },
"auth-http-port": 1000,
"auth-https-port": 1003,
"auth-keepalive": "disable",
"policy-auth-concurrent": 0,
"auth-session-limit": "block-new",
"auth-cert": { "q_origin_key": "Fortinet_Factory",
"name": "Fortinet_Factory",
"datasource": "certificate.local" },
"clt-cert-req": "disable",
"fortiservice-port": 8013,
"cfg-save": "automatic",
"cfg-revert-timeout": 600,
"reboot-upon-config-restore": "enable",
"admin-scp": "enable",
"security-rating-result-submission": "enable",
"security-rating-run-on-schedule": "enable",
"wireless-controller": "enable",
"wireless-controller-port": 5246,
"fortiextender-data-port": 25246,
"fortiextender": "disable",
"fortiextender-vlan-mode": "disable",
"switch-controller": "disable",
"switch-controller-reserved-network": "169.254.0.0 255.255.0.0",
"dnsproxy-worker-count": 1,
"url-filter-count": 1,
"proxy-worker-count": 0,
"scanunit-count": 0,
"proxy-kxp-hardware-acceleration": "enable",
"proxy-cipher-hardware-acceleration": "enable",
"fgd-alert-subscription": "advisory latest-threat",
"ipv6-accept-dad": 1,
"ipv6-allow-anycast-probe": "disable",
"csr-ca-attribute": "enable",
"wimax-4g-usb": "disable",
"cert-chain-max": 8,
"sslvpn-max-worker-count": 0,
"sslvpn-plugin-version-check": "enable",
"two-factor-ftk-expiry": 60,
"two-factor-email-expiry": 60,
"two-factor-sms-expiry": 60,
"two-factor-fac-expiry": 60,
"two-factor-ftm-expiry": 72,
"per-user-bwl": "disable",
"virtual-server-count": 0,
"virtual-server-hardware-acceleration": "enable",
"wad-worker-count": 0,
"wad-csvc-cs-count": 1,
"wad-csvc-db-count": 0,
"wad-source-affinity": "enable",
"wad-memory-change-granularity": 10,
"login-timestamp": "disable",
"miglogd-children": 0,
"special-file-23-support": "disable",
"log-uuid-policy": "enable",
"log-uuid-address": "disable",
"log-ssl-connection": "disable",
"arp-max-entry": 131072,
"av-affinity": "0",
"wad-affinity": "0",
"ips-affinity": "0",
"miglog-affinity": "0",
"url-filter-affinity": "0",
"ndp-max-entry": 0,
"br-fdb-max-entry": 8192,
"max-route-cache-size": 0,
"ipsec-soft-dec-async": "disable",
"device-idle-timeout": 300,
"gui-device-latitude": "52.5167",
"gui-device-longitude": "13.4",
"private-data-encryption": "disable",
"auto-auth-extension-device": "enable",
"gui-theme": "mariner",
"gui-date-format": "yyyy\/MM\/dd",
"gui-date-time-source": "system",
"igmp-state-limit": 3200,
"cloud-communication": "enable",
"fec-port": 50000,
"fortitoken-cloud": "enable" },
"vdom": "root",
"path": "system",
"name": "global",
"status": "success",
"http_status": 200,
"serial": "FGTAWS0007B7604F",
"version": "v6.2.6",
"build": 1175 }
*/
